### ISSUE TITLE
Use common apsync hostname

### ISSUE THREAD

**Issue by peterbarker** [ArduPilot/companion#14]

**Comment by magicrub** [comment]
Please provide a description.

**Comment by rmackay9** [comment]
@magicrub, don't worry too much.. i think these are mostly issues that Peter is raising for himself..

**Comment by magicrub** [comment]
It's the habit I'm worried about. Same problem with PRs.

**Comment by peterbarker** [comment]
Images for RPi and Edison now do this.

TX1 to follow.

**Comment by peterbarker** [comment]
TX1 followed.  All APSync images now use hostname apsync
