### ISSUE TITLE
Porting to Joule

### ISSUE THREAD

**Issue by griz1112** [ArduPilot/companion#28]
I want to port this over to Joule but where do I get the source for the image? I'm wondering why you are putting this out as an image and not a deb file. If you use checkinstall to build your binaries it will create the deb for you. Then you could use apt-get locally to install it like any other package. Or dpkg on systems without apt-get. Seems to me this would be a lot easier for the end user to install as you could add in the commands to install the image in your scripts.

**Comment by davidbuzz** [comment]
Having a .deb is a great idea... Sounds like u just volunteered to create one... and i just volunteered to test it.. i have edison and pi but not Joule.

**Comment by griz1112** [comment]
I can do that. Philip sent me the board for a different project and I asked Randy about a Joule port he said it would not be a big deal. Might as well get that done while I have it. I have an edison Pi's Tk1 TX1 TX2 and probably a dozen more. About the only popular one I don't have is beagleboard black. So yea we are on the same team just working in different areas. So I can make debs for all of those. Recently I ran into this package called checkinstall. You run a make doing checkinstall make package. It creates docs and a deb file if you want and also really checks the package for any issues. I've been looking at it for packaging the SLAM system I've done debs before but its been close to 20 years. I'm sure its changed some everything else in linux has.

**Comment by jmachuca77** [comment]
There are scripts available to create and install all that is needed. You can use the scripts for the TX1/Ubuntu, with slight modifications to port to the Joule. They are available on the companion repo:

https://github.com/ArduPilot/companion/tree/master/Nvidia_JTX1/Ubuntu <https://github.com/ArduPilot/companion/tree/master/Nvidia_JTX1/Ubuntu>

Best regards,

Jaime Machuca Mercado
CTO | Droidika | www.Droidika.com
Mail. Jaime@Droidika.com
Tel. +52 (33) 3777 5327
Cel. +52 1 (33) 3945 3350






Este correo electrónico y cualquier archivo transmitido en él, son confidenciales y para uso exclusivo de los individuos y entidades a quienes está dirigido. Si usted no es el destinatario previsto o la persona encargada de recibirlo, y tiene por error este mensaje, queda prohibido y sin validez el uso, difusión, re-envío, reimpresión o copia. Toda oferta y/o aceptación de propuestas comerciales, celebración de contratos u otros actos tendientes a la adquisición de bienes o servicios, así como el establecimiento de cualquier clase de obligación legal para Droidika S.A. de C.V., deberá confirmarse por escrito firmado autógrafamente por funcionario competente, excepto que se cuente con un contrato vigente que autorice el uso de este medio para tales fines. Si usted recibió este correo por equivocación, favor de notificar inmediatamente por este medio a su remitente, y después borrarlo de su correo

**Comment by griz1112** [comment]
Found out yesterday the MakerFaire demo is on so not going to have a spare minute for the next month. Looked through it quickly and it looks like it more editing config files than a lot of programs to package up. Here is the way I know how to package up a lot of files spread over a file system. It makes a deb that will install everything in the correct places. http://www.sj-vs.net/creating-a-simple-debian-deb-package-based-on-a-directory-structure/ I'll get to it as soon as I get back but if one of you wants to give it a go before then that page will get you through it.

**Comment by auturgy** [comment]
suggest close, noting joule is dead

**Comment by peterbarker** [comment]
Agreed.
