### ISSUE TITLE
Support for 5.8 wifi with Edison running ApSync

### ISSUE THREAD

**Issue by mtbsteve** [ArduPilot/companion#29]
I order to minimize risk of using wifi for telemetry  in combination with a 2.4 RC controller, it would be great if ApSync would support the 5.8 capabilities of the built in wifi of the Edison companion computer. 
Looking at 
https://github.com/ArduPilot/companion/blob/master/Common/Ubuntu/3_wifi_access_point.sh 
it seems that the ApSync access point is hardcoded to the 2.4 b/g band only while eg the Edison hardware also supports the 5.8 band. Ideally ApSync would support the user to configure the wifi settings.

**Comment by jmachuca77** [comment]
Intel Edison was discontinued and is no longer supported
