### ISSUE TITLE
GSoC Idea for Live Video Improvements in APSync

### ISSUE THREAD

**Issue by shortstheory** [ArduPilot/companion#34]
As the title suggests, I am interested in applying to ArduPilot for working on the above project. I have been looking at the code of both the companion repository and the Intel Camera Streaming Daemon and I have some questions:

* Is the target to redo the streaming performed by `apsync.py`? Currently, it only streams a single bitrate video stream to the target GCS. From my understanding, the project aims to support multiple cameras, so it might be a good idea to go down a path similar to ICSD. This has its codebase in C++ and I want to know if the goal is to redo APSync in Python or in C++.
* Currently, `apsync.py` uses a UDP stream for streaming video. QGroundControl supports multiple types of video streaming including RTSP. Using an RTSP video stream can provide us with more options for automatically modifying the bitrate according to bandwidth reports from RTCP QoS packets. Is it alright to rework APSync to provide an RTSP option to support this?
* Is there a goal of multicast video (i.e., one UAV streaming to multiple GCS) for this project?
* What board specific optimisations can I look into? The TX1 is clearly the most powerful out of APSync supported boards and can give us much more options for encoding video than we can get from an RPi3.

Thanks for reading this!

**Comment by jmachuca77** [comment]
@shortstheory Thanks for submiting your proposal to GSoC, how ever the issues list here is for reporting issues with the code or requesting new features, etc. For now please keep any GSoC related communications on the GSoC site, Gitter channel or Discuss server. Thanks!
