### ISSUE TITLE
Network manager SSH issues

### ISSUE THREAD

**Issue by OxMarco** [ArduPilot/companion#37]
After running the script 2_use_networkmanager.sh the raspberry pi 3 becomes unreachable either via WiFi or SSH.
Working on a clean Raspian installation.

**Comment by peterbarker** [comment]
On Mon, 18 Jun 2018, Giammarco R. Casanova wrote:

> After running the script 2_use_networkmanager.sh the raspberry pi 3 becomes
> unreachable either via WiFi or SSH.
> Working on a clean Raspian installation.

A reboot is required to have the access point come up.

It should still come up on an ethernet network you plug it into (I usually 
use "ssh apsync.local" to find it).

**Comment by OxMarco** [comment]
I rebooted via ssh as suggested, then tried to reconnect but nothing. I even forcefully disconnected and reconnected the Pi to the network and to the power supply but it seems unresponsive.
I think the network manager used somehow scrambled SSH and WiFi connectivity.
Connecting to a screen the Pi works seamlessly but WiFi and SSH interfaces are down and inaccessible

I will try to flash the SD card and reinstall everything. Is the network manager needed? I don't plan to use the WiFi hotspot functionality, just the 3G connection.

**Comment by OxMarco** [comment]
okay the issue was solved by rebooting (manually) and plugging in the ethernet cable after the Pi startup. Thanks anyway
